### ISSUE TITLE
S3 logs

### ISSUE THREAD

**Issue by moshloop** [flanksource/apm-hub#20]

**Comment by moshloop** [comment]
```yaml
s3:
   - labels:
         host: acmehost
      type: AccessLog   
     path:
        - s3://bucket/folder/logs.log
````
A query with labels host=achmehost will then read logs from the file, line by line
