### ISSUE TITLE
Server side logs

### ISSUE THREAD

**Issue by moshloop** [flanksource/apm-hub#30]
Add a new log backend for retrieving logs on disk:

```yaml
file:
   - labels:
         name: acmehost
         type: Nginx
     path:
        - /var/log/access.log
```

A query with labels `name=achmehost,type=Nginx` will then read logs from the file, line by line
