### ISSUE TITLE
Incorrect parsing of backends from the configuration file

### ISSUE THREAD

**Issue by adityathebe** [flanksource/apm-hub#48]
A new bug was introduced in a recent PR https://github.com/flanksource/apm-hub/pull/38/files due to which backend configuration is incorrectly parsed.

```yaml
backends:
  - file:
    kubernetes:
    opensearch:
```

If multiple backends are provided as a single list item, then only one of the backend is selected because the other ones get overwritten.

The parsing function expects the config to be this way

```yaml
backends:
  - file:
  - kubernetes:
  - opensearch:
```

To be specific this function is buggy
```go
func AttachSearchAPIToBackend(kommonsClient *kommons.Client, backend *logs.SearchBackend) error {
```
